config/routes.rb
Hiboxing::Application.routes.draw do
  
  namespace :admin do
    get '' => 'admin#index', as: "/"
    resources :news_items
    resources :photos
    resources :users
    resources :groups
    resources :events
    resources :coaches
    resources :gyms
    resources :gym_images, only: [:create, :index, :destroy]
    
    resources :sportsmen do
      resources :subs do
        resources :visits
      end
    end
    
    controller :session do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end
  
  resources :sportsmen, only: [:create, :new, :show, :edit]
  
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :photos, only: [:index]
  resources :news_items, only: [:index]
  resources :gyms, only: [:index]
  resources :coaches, only: [:index]
  controller :pages do
    get :about
    get :school
  end

  controller :club do
    get :index
  end

  root :to => 'club#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :image, :title
  
  mount_uploader :image, ImageUploader
  
  validates :title, presence: true
  validates :image, presence: true
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ApplicationController

  before_filter :set_photo, only: [:edit,:update,:destroy]
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end
  
  def edit
    render :new
  end
  
  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to admin_photos_path, notice: 'Фото добавлено'
    else
      render :new, notice: 'Не удалось добавить фото'
    end
  end
  
  def update
    if @photo.update_attributes(params[:photo])
      redirect_to admin_photos_path, notice: 'Фото изменено'
    else
      render :new, notice: 'Не удалось сохранить изменения для фото'
    end
  end
  
  def destroy
    @photo.destroy
    redirect_to admin_photos_path
  end
  
  protected
  
  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/_form.html.erb
<div id="photo_form">
  <%= form_for [:admin,@photo], html: { multipart: true } do |f| %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :title, 'Заголовок' %>
    <%= f.text_field :title %>
    
    <%= f.label :description, 'Описание' %>
    <%= f.text_area :description %>
    
    <%= f.label :image, 'Файл' %>
    <%= f.file_field :image %>
    
    <%= f.submit 'Сохранить' %>
  <% end %>
</div>

app/views/admin/photos/_photo.html.erb
<div id="photo_<%= photo.id %>">
  <%= image_tag photo.image.thumb, alt: photo.title %>
  <%= link_to 'Редактировать', edit_admin_photo_path(photo.id) %>
  <%= link_to 'Удалить', admin_photo_path(photo.id), method: :delete %>
</div>

app/views/admin/photos/index.html.erb
<h2>Фотографии</h2>

<div id="photos">
  <%= link_to 'Добавить фото', new_admin_photo_path %>
  <%= render @photos %>
</div>

app/views/admin/photos/new.html.erb
<div id="photo_form">
  <%= render 'form' %>
</div>