config/routes.rb
Hiboxing::Application.routes.draw do
  
  namespace :admin do
    get '' => 'admin#index', as: "/"
    resources :news_items
    resources :photos
    resources :users
    resources :groups
    resources :events
    resources :coaches
    resources :gyms
    resources :gym_images, only: [:create, :index, :destroy]
    
    resources :sportsmen do
      resources :subs do
        resources :visits
      end
    end
    
    controller :session do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end
  
  resources :sportsmen, only: [:create, :new, :show, :edit]
  
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :photos, only: [:index]
  resources :news_items, only: [:index]
  resources :gyms, only: [:index]
  resources :coaches, only: [:index]
  controller :pages do
    get :about
    get :school
  end

  controller :club do
    get :index
  end

  root :to => 'club#index'

end

app/controllers/admin/sportsmen_controller.rb
class Admin::SportsmenController < Admin::ApplicationController
  def index
    @sportsmen = Sportsman.all
  end

  def show
    @sportsman = Sportsman.find(params[:id])
  end

  def new
    @sportsman = Sportsman.new
  end

  def create
    @sportsman = Sportsman.new(params[:sportsman])
    if @sportsman.save
      redirect_to admin_sportsmen_url, :notice => "Спортсмен добавлен"
    else
      render :action => 'new'
    end
  end

  def edit
    @sportsman = Sportsman.find(params[:id])
  end

  def update
    @sportsman = Sportsman.find(params[:id])
    if @sportsman.update_attributes(params[:sportsman])
      redirect_to admin_sportsmen_url, :notice => "Спортсмен изменен"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @sportsman = Sportsman.find(params[:id])
    @sportsman.destroy
    redirect_to admin_sportsmen_url, :notice => "Спортсмен удален"
  end
end

app/controllers/sportsmen_controller.rb
class SportsmenController < ApplicationController
  def create
    @sportsman = Sportsman.new(params[:sportsman])
    if @sportsman.save
      #log in created user
      session[:sportsman_id] = @sportsman.id
      redirect_to edit_sportsman_path(@sportsman), notice: 'Добро пожаловать!'
    else
      render :new, notice: 'Не получилось)'
    end
  end
  
  def new
    @sportsman = Sportsman.new(params[:sportsman])
  end
  
  def show
    @sportsman = Sportsman.find(params[:id])
  end
  
  def edit
    if session[:sportsman_id]
      @sportsman = Sportsman.find(session[:sportsman_id])
    else
      redirect_to login_url, notice: 'Авторизуйтесь'
    end
  end
end

app/helpers/admin/sportsmen_helper.rb
module Admin::SportsmenHelper
end

app/views/admin/sportsmen/_form.html.erb
<%= form_for [:admin, @sportsman] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name, 'Имя' %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :phone, 'Телефон' %><br />
    <%= f.text_field :phone %>
  </p>
  <p><%= f.submit 'Сохранить' %></p>
<% end %>

app/views/admin/sportsmen/edit.html.erb
<% title "Управление спортсменом" %>

<%= render 'form' %>

<div class="active-subs">
  <h3>Абонементы</h3>
  <%= render @sportsman.subs.active %>
</div>

<div class="inactive-subs">
  <h3>Неактивные абонементы</h3>
  <%= render @sportsman.subs.inactive %>
</div>

<p>
  <%= link_to "Выписать абонемент", new_admin_sportsman_sub_path(@sportsman) %> |
  <%= link_to "View All", admin_sportsmen_path %>
</p>

app/views/admin/sportsmen/index.html.erb
<% title "Спортсмены" %>

<table>
  <tr>
    <th>Имя</th>
    <th>Телефон</th>
  </tr>
  <% for sportsman in @sportsmen %>
    <tr>
      <td><%= link_to sportsman.name, edit_admin_sportsman_path(sportsman) %></td>
      <td><%= sportsman.phone %></td>
      <td><%= link_to "Удалить", admin_sportsman_path(sportsman), :confirm => 'Уверены?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Добавить", new_admin_sportsman_path %></p>

app/views/admin/sportsmen/new.html.erb
<% title "New Admin/Sportsman" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_sportsmen_path %></p>

app/views/admin/sportsmen/show.html.erb
<% title "Admin/Sportsman" %>

<p>
  <strong>Name:</strong>
  <%= @sportsman.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @sportsman.phone %>
</p>

<p>
  <%= link_to "Edit", edit_admin_sportsman_path(@sportsman) %> |
  <%= link_to "Destroy", admin_sportsman_path(@sportsman), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_sportsmen_path %>
</p>