config/routes.rb
Hiboxing::Application.routes.draw do
  
  namespace :admin do
    get '' => 'admin#index', as: "/"
    resources :news_items
    resources :photos
    resources :users
    resources :groups
    resources :events
    resources :coaches
    resources :gyms
    resources :gym_images, only: [:create, :index, :destroy]
    
    resources :sportsmen do
      resources :subs do
        resources :visits
      end
    end
    
    controller :session do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end
  
  resources :sportsmen, only: [:create, :new, :show, :edit]
  
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :photos, only: [:index]
  resources :news_items, only: [:index]
  resources :gyms, only: [:index]
  resources :coaches, only: [:index]
  controller :pages do
    get :about
    get :school
  end

  controller :club do
    get :index
  end

  root :to => 'club#index'

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :description, :image, :name
  mount_uploader :image, CoachUploader
  validates :name, presence: true
  validates :image, presence: true
  
  def first_name
    name.split.first
  end
  
  def last_name
    name.split.last
  end
end

app/controllers/admin/coaches_controller.rb
class Admin::CoachesController < Admin::ApplicationController
  before_filter :set_coach, only: [:edit,:update,:destroy]
  def index
    @coaches = Coach.all
  end
  
  def new
    @coach = Coach.new
  end
  
  def edit
    render :new
  end
  
  def create
    @coach = Coach.new(params[:coach])
    if @coach.save
      redirect_to admin_coaches_url, notice: 'Тренер добавлен'
    else
      render :new, notice: 'Ошибка при добавлении тренера'
    end
  end
  
  def update
    if @coach.update_attributes(params[:coach])
      redirect_to admin_coaches_url, notice: 'Тренер изменен'
    else
      render :new, notice: 'Ошибка при сохранении тренера'
    end
  end
  
  def destroy
    @coach.destroy
    redirect_to admin_coaches_url
  end
  
  protected
  
  def set_coach
    @coach = Coach.find(params[:id])
  end
end

app/helpers/coaches_helper.rb
module CoachesHelper
  def render_name_as_first_and_last(name)
    [
      (content_tag :p, name.split(" ").first, class: "name"),
      (content_tag :p, name.split(" ").last, class: "last")
    ].join("</br>").html_safe
  end
end

app/views/admin/coaches/_coach.html.erb
<div class="coach" id="<%= coach.id %>">
  <%= coach.name %>
  <%= link_to 'Редактировать', edit_admin_coach_path(coach.id) %>
  <%= link_to 'Удалить', admin_coach_path(coach.id), method: :delete %>
</div>

app/views/admin/coaches/_form.html.erb
<%= form_for [:admin,@coach], multipart: true do |f| %>
  <%= f.label :name, 'Имя' %>
  <%= f.text_field :name %>
  
  <%= f.label :description, 'Текст' %>
  <%= f.text_area :description %>
  
  <%= f.label :image, 'Фото' %>
  <%= f.file_field :image %>
  
  <%= f.submit 'Сохранить' %>
<% end %>

app/views/admin/coaches/crop.html.erb
<h1>Обработка фотографии</h1>

<%= image_tag @coach.image_url, id: 'cropbox' %>

<%= form_for [:admin,@coach] do |f| %>
  <% %w[w h x y].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Обрезать" %>
  </div>
<% end %>

app/views/admin/coaches/index.html.erb
<%= link_to 'Добавить', new_admin_coach_path %>

<%= render @coaches %>

app/views/admin/coaches/new.html.erb
<div class="hiboxing_form">
  <%= render 'form' %>
</div>